schema_version: '2.0'
directory_name: instruction
description: The instruction directory is a Python package containing instruction
  modules and functionality. It provides a structured collection of related code organized
  for easy import and use.
semantic_scope:
- instruction
files:
- __init__.py
- engine.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .py: 2
    .yaml: 1
