schema_version: '2.0'
directory_name: gpt
description: gpt
semantic_scope:
- gpt
files:
- CIP_GPT_architecturev2.md
- git_action.yaml
- gpt_resource_guide.yaml
- how_to_use_gpt.md
- metadata_architecturev3.md
- privacy-policy.md
- prompt.txt
child_directories: []
