schema_version: '2.0'
directory_name: schemas
description: The schemas directory defines the data schemas and validation rules for
  CIP metadata. It contains YAML schema definitions and validation logic for meta.yaml
  files and other CIP structures.
semantic_scope:
- schemas
files:
- __init__.py
- filename_tags.py
- meta_yaml.py
- repository.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 5
  directory_count: 0
  primary_file_types:
    .py: 4
    .yaml: 1
