schema_version: '2.0'
directory_name: utils
description: This directory contains utility code for CIP-Core operations.
semantic_scope:
- ai/ml
- implementation
- utility
files:
- __init__.py
child_directories:
- __pycache__
