schema_version: '2.0'
directory_name: vm
description: The vm directory is a Python package containing vm modules and functionality.
  It provides a structured collection of related code organized for easy import and
  use.
semantic_scope:
- vm
files:
- __init__.py
- service.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .py: 2
    .yaml: 1
