schema_version: '2.0'
directory_name: architecture
description: The architecture directory contains documentation and readme files for
  architecture. It provides essential information, guides, and reference materials
  to help users understand and work with this component.
semantic_scope:
- architecture
files:
- core-design.md
- README.md
child_directories:
- legacy
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 1
  primary_file_types:
    .md: 2
    .yaml: 1
