schema_version: '2.0'
directory_name: engine
description: The engine directory contains the core engine components for the CIP
  system. This includes the main execution engine, metadata processing, and orchestration
  logic that coordinates all CIP operations.
semantic_scope:
- engine
files:
- __init__.py
- config.py
- core.py
- repository.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 5
  directory_count: 0
  primary_file_types:
    .py: 4
    .yaml: 1
