schema_version: '2.0'
directory_name: templates
description: The templates directory contains two configuration files for a VM (Virtual
  Machine) - vm-config.yaml and meta.yaml.
semantic_scope:
- virtual machine
- cloud computing
- configuration file
- template
files:
- vm-config.yaml
child_directories: []
