schema_version: '2.0'
directory_name: migration-guides
description: The migration-guides directory is reserved for guides functionality.
  It provides a dedicated space for organizing related files and components.
semantic_scope:
- guides
- migration
files: []
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 1
  directory_count: 0
  primary_file_types:
    .yaml: 1
