schema_version: '2.0'
directory_name: automation-workflows
description: The automation-workflows directory is reserved for automation functionality.
  It provides a dedicated space for organizing related files and components.
semantic_scope:
- automation
- workflows
files: []
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 1
  directory_count: 0
  primary_file_types:
    .yaml: 1
