schema_version: '2.0'
directory_name: docs
description: The docs directory contains project documentation, user guides, and reference
  materials. It serves as the central hub for all written materials that help users
  understand and work with the project.
semantic_scope:
- documentation
- guides
files:
- EXAMPLES.md
- QUICK_START.md
- README.md
- WHY_CIP.md
child_directories:
- architecture
- case-studies
- examples
- gpt
- limitations
- reference
- scripts
- technical
- user-guide
generation_context:
  generator: ai_enhanced
  file_count: 5
  directory_count: 9
  primary_file_types:
    .md: 4
    .yaml: 1
